name: lifepro_new
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.0
  flutter_secure_storage: ^9.2.4
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.2
  lottie: ^3.3.2
  google_fonts: ^6.3.3
  flutter_animate: ^4.5.2
  connectivity_plus: ^6.1.1
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  geolocator: ^13.0.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#071B1B"
  image: assets/image/logo/logo.png
  android_12:
    color: "#071B1B"
    image: assets/image/logo/logo.png
  ios: true
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/image/logo/
